#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the compareTriplets function below.
def compareTriplets(a, b):
    san = []
    o = 0
    j = 0
    for i in range(0, len(a)):
        
        if a[i] > b[i]:
            o = o +1
        elif b[i] > a[i]:
            j = j +1
        else:
            continue
        
    san.append(o)
    san.append(j)
    return san

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()

