#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    positive = negative = zero = 0
    
    for j in range(n):
        if arr[j] > 0:
            positive += 1
        elif arr[j]:
            negative += 1
        else:
            zero += 1
    
    print(positive / n)
    print(negative / n)
    print(zero / n)
    
if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)

